# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  mouseEvents: false
  expandFocusedSidePanel: true
  showNumstatInFilesView: true
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: always
    pager: >
      delta
      --dark --paging=never --line-numbers
      --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

  # If true, do not spawn a separate process when using GPG
  overrideGpg: true

  commitPrefix: []
  commitPrefixes: {}
  branchPrefix: ""

promptToReturnFromSubprocess: false
