[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"

[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"

[".config/tmux/themes/catppuccin"]
    type = "git-repo"
    url = "https://github.com/catppuccin/tmux"
    refreshPeriod = "168h"

[".config/delta/themes.gitconfig"]
    type = "file"
    url = "https://raw.githubusercontent.com/dandavison/delta/main/themes.gitconfig"
    refreshPeriod = "168h"
