"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$directory\
$git_branch\
$username\
$container\
$docker_context\
$nodejs\
$python\
$rust\
$package\
$aws
$sudo\
$git_state\
$git_status\
($jobs$container$git_metrics)\
$character
"""

right_format = """
$cmd_duration\
$time\
$battery\
$status
"""

continuation_prompt = "[▸▹ ](dimmed color_fg0)"

add_newline = true
palette = 'tokyonight'

[palettes.tokyonight]
color_fg0 = "#c0caf5"
color_bg1 = "#1f2335"
color_bg2 = "#414868"
color_blue = "#7aa2f7"
color_aqua = "#7dcfff"
color_green = "#c3e88d"
color_orange = "#ff9e64"
color_purple = "#bb9af7"
color_red = "#ff007c"
color_yellow = "#ffc777"

[character]
format = "$symbol "
success_symbol = '[ ](bold fg:color_green)'
error_symbol = '[ ](bold fg:color_red)'
vimcmd_symbol = '[ ](bold fg:color_yellow)'
vimcmd_replace_one_symbol = '[ ](bold fg:color_purple)'
vimcmd_replace_symbol = '[ ](bold fg:color_purple)'
vimcmd_visual_symbol = '[ ](bold fg:color_yellow)'


# Segment configurations
[aws]
symbol = '  '

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "█"
charging_symbol = "[↑](italic bold fg:color_green)"
discharging_symbol = "↓"
unknown_symbol = "░"
empty_symbol = "▃"

[[battery.display]]
threshold = 20
style = "italic bold fg:color_red"

[[battery.display]]
threshold = 60
style = "italic dimmed fg:color_purple"

[[battery.display]]
threshold = 70
style = "italic dimmed fg:color_yellow"

[cmd_duration]
style = "italic fg:color_fg0"
format = "[◄ $duration ]($style)"

[container]
format = '[$symbol \[$name\]]($style) '

[directory]
truncation_length = 3
truncation_symbol = "…/"
use_os_path_sep = true
read_only = " 󰌾"
style = "fg:color_blue"
format = "[ $path ]($style)[$read_only]($read_only_style)"
repo_root_style = "fg:color_aqua bold"
repo_root_format = """
[$before_root_path]($before_repo_root_style)\
[$repo_root]($repo_root_style)\
[$path]($style)\
[$read_only]($read_only_style)\
"""

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[docker_context]
disabled = true
symbol = " "
format = '[$symbol$context](color_blue bold) '

[git_branch]
symbol = "  "
style = "italic fg:color_red"
format = '[[$symbol](fg:color_aqua)$branch(:$remote_branch)]($style) '
truncation_symbol = "⋯"
truncation_length = 11

[git_commit]
tag_symbol = '  '

[git_metrics]
disabled = false
format = '([▴$added]($added_style) )([▿$deleted]($deleted_style) )'
added_style = 'italic dimmed fg:color_green'
deleted_style = 'italic dimmed fg:color_red'
ignore_submodules = true

[git_status]
style = "bold italic fg:color_yellow"
format = '[($all_status$ahead_behind )]($style)'

[hostname]
ssh_symbol = " "

[jobs]
style = "fg:color_fg0"
symbol = "[▶](fg:color_blue italic)"
format = "[$symbol$number]($style) "

[nodejs]
symbol = " "
format = '[$symbol$version](bold color_green) '

[os]
disabled = false
format = '[$symbol ]($style)'
style = "fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[package]
disabled = false
symbol = "󰏗 "
format = '[$symbol$version](color_orange bold) '

[python]
symbol = " "
format = '[$symbol$version \($virtualenv\)](bold color_yellow) '

[rust]
symbol = "󱘗 "

[sudo]
disabled = false
style = "bold fg:color_blue"
format = "[$symbol]($style)"

[time]
disabled = false
style = "italic dimmed fg:color_fg0"
format = "[$time ]($style)"
time_format = "%R"
utc_time_offset = "local"

[username]
show_always = false
style_user = "fg:color_yellow bold italic"
style_root = "fg:color_purple bold italic"
format = '[ $user ]($style)'
